kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: worker-user-data
  type: Opaque
  commands:
    userData: "cat worker-user-data.yaml"
    postprocessor: "printf ct"
- name: master-user-data
  type: Opaque
  commands:
    userData: "cat master-user-data.yaml"
    postprocessor: "printf ct"

namespace: openstack-provider-system
