kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: worker-user-data
  type: Opaque
  files:
    - userData=worker-user-data.yaml
  literals:
    - postprocessor=ct
- name: master-user-data
  type: Opaque
  files:
    - userData=master-user-data.yaml
  literals:
    - postprocessor=ct

namespace: openstack-provider-system
